### ISSUE TITLE
Update Definitions?

### ISSUE THREAD

**Issue by Brutalbeard** [zengfenfei/ringcentral-ts#8]
Hey there!

Any way you would be ok with writing out directions on updating definitions and paths?

**Comment by tylerlong** [comment]
@Brutalbeard I think @zengfenfei has discontinued this project. I do have the plan to create a TS SDK for RingCentral but I need to find some time.

**Comment by zengfenfei** [comment]
@Brutalbeard @zengfenfei I can transfer this project and the ownership of the npm module to any of you.

**Comment by Brutalbeard** [comment]
Feel free to send it to me! And thank you Kevin!
